### ISSUE TITLE
fix error GitHub Actions Error.

### ISSUE THREAD

**Issue by acquayefrank** [qgofer/qgoferutils#6]

**Comment by laudb** [comment]
hi @acquayefrank, cool project!
 I see under actions that the CI workflow, managed by https://github.com/qgofer/qgoferutils/actions/workflows/test.yaml, displays the error, is this where you would like fixed?

**Comment by laudb** [comment]
@acquayefrank okay got it, this helps alot, thank you

**Comment by acquayefrank** [comment]
The black Issue has been resolved, I think this time it's failing due to version mismatch of nbdev.

**Comment by acquayefrank** [comment]
The deployment process has changed a bit so this is no longer necesary, I plan on adding a unit test flow to the pipeline soon but for now. I think this should be closed.
